# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# Specify additional command line arguments
- arguments: [-XGHC2021, -XOverloadedStrings, -XLambdaCase]

# Warn on use of partial functions
- group: {name: partial, enabled: true}
